CREATE DATABASE BANCONE
USE BANCONE

CREATE TABLE SERVICIO(
CLAVE_SERVICIO INT PRIMARY KEY,
NOMBRE_SERV VARCHAR(150))

DROP TABLE SERVICIO

CREATE TABLE EJECUTIVO_CUENTA(
NUM_EMP INT PRIMARY KEY,
NOMBRE_EMP VARCHAR(150),
DIRECCION_EMP VARCHAR(150),
FECHA_INGRESO DATETIME,
FECHA_NACIMIENTO DATETIME,
FECHA_TERMINO_CONTRATO DATETIME)

INSERT INTO EJECUTIVO_CUENTA VALUES(25,'VIRGINA','REFORMA','19/04/96','19/04/68','20/12/97')
INSERT INTO EJECUTIVO_CUENTA VALUES(21,'alejandro','coyuya','19/04/98','19/04/88','20/12/2000')

SELECT *
FROM EJECUTIVO_CUENTA

CREATE TABLE CLIENTE(
NIP INT PRIMARY KEY,
NOMBRE_CLI VARCHAR(150),
fechaNacimiento FLOAT)


INSERT INTO CLIENTE VALUES(34,'JUANITO',3500,2500)
INSERT INTO CLIENTE VALUES(35,'JUANITO',3500,2500)

CREATE TABLE TIPO_TARJETA(
ID_TIPO INT PRIMARY KEY,
TIPO_TARJETA VARCHAR(150))

INSERT INTO TIPO_TARJETA VALUES(55,'NOMINA')
INSERT INTO TIPO_TARJETA VALUES(56,'DEBITO')
INSERT INTO TIPO_TARJETA VALUES(57,'CREDITO')



CREATE TABLE CLI_EJEC(
NUM_CLI3 INT,
NUM_EMP1 INT,
CONSTRAINT FK_NOCLI3 FOREIGN KEY(NUM_CLI3) REFERENCES CLIENTE(NIP),
CONSTRAINT FK_NUMEMP FOREIGN KEY(NUM_EMP1) REFERENCES EJECUTIVO_CUENTA(NUM_EMP))


CREATE TABLE CLI_SERVICIO(
NUM_CLI1 INT,
NUM_SER1 INT,
CONSTRAINT FK_NOCLI1 FOREIGN KEY(NUM_CLI1) REFERENCES CLIENTE(NIP),
CONSTRAINT FK_CLASERV FOREIGN KEY(NUM_SER1) REFERENCES SERVICIO(CLAVE_SERVICIO))


CREATE TABLE CLI_TIPOTAR(
NUM_CLI2 INT,
NUM_TT1 INT,
CLAVE_TARJETA INT,
FECHA_APERTURA DATETIME,
SALDO float,
CONSTRAINT FK_NOCLI2 FOREIGN KEY(NUM_CLI2) REFERENCES CLIENTE(NIP),
CONSTRAINT FK_NUMTT1 FOREIGN KEY(NUM_TT1) REFERENCES TIPO_TARJETA(ID_TIPO))

