CREATE DATABASE PEDIDO1
USE PEDIDO1


CREATE TABLE CALLE(
ID_CA INT,
NOM_CAL VARCHAR(150),
CONSTRAINT PK_IDCA PRIMARY KEY(ID_CA))

CREATE TABLE COMUNA(
ID_CO INT,
NOM_CO VARCHAR(150),
CONSTRAINT PK_IDCO PRIMARY KEY(ID_CO))

CREATE TABLE CIUDAD(
ID_CD INT,
NOM_CD VARCHAR(150),
CONSTRAINT PK_IDCD PRIMARY KEY(ID_CD))

CREATE TABLE CLIENTE(
NUM_CL INT,
SALDO_CL FLOAT,
LIMCL FLOAT,
DESCUENTO FLOAT,
CHECK(LIMCL<=3000000),
CHECK(SALDO_CL<=LIMCL),
CONSTRAINT PK_NUMCL PRIMARY KEY(NUM_CL))

CREATE TABLE DIRECCION(
NUM_DIR INT,
ID_CA1 INT,
ID_CO1 INT,
ID_CD1 INT,
NUM_CL1 INT,
CONSTRAINT FK_IDCA1 FOREIGN KEY(ID_CA1) REFERENCES CALLE(ID_CA),
CONSTRAINT FK_IDCO1 FOREIGN KEY(ID_CO1) REFERENCES COMUNA(ID_CO),
CONSTRAINT FK_IDCD1 FOREIGN KEY(ID_CD1) REFERENCES CIUDAD(ID_CD),
CONSTRAINT FK_IDCL1 FOREIGN KEY(NUM_CL1)REFERENCES CLIENTE(NUM_CL))


CREATE TABLE FABRICA(
NUM_FA INT,
NOM_FA VARCHAR(150),
TEL_FAC VARCHAR(50),
CONSTRAINT PK_NUMFA PRIMARY KEY(NUM_FA))

CREATE TABLE ARTICULO(
NUM_ART INT,
DESC_ART VARCHAR(150),
CONSTRAINT PK_NUMART PRIMARY KEY(NUM_ART))

CREATE TABLE  CLI_ART(
NUM_ART1 INT,
NUM_CL2 INT,
FECHA_P DATETIME,
CANTIDAD INT,
PRECIO FLOAT,
CONSTRAINT FK_NUMART1 FOREIGN KEY(NUM_ART1) REFERENCES ARTICULO(NUM_ART),
CONSTRAINT FK_NUMCL2 FOREIGN KEY(NUM_CL2) REFERENCES CLIENTE(NUM_CL))

CREATE TABLE ART_FA(
NUM_ART2 INT,
NUM_FA1 INT,
EXISTENCIAS INT,
TIPO_FABRICA VARCHAR(150),
CONSTRAINT FK_NUMART2 FOREIGN KEY(NUM_ART2) REFERENCES ARTICULO(NUM_ART),
CONSTRAINT FK_NUMFA FOREIGN KEY(NUM_FA1) REFERENCES FABRICA(NUM_FA),
CHECK(TIPO_FABRICA='PROCEDENCIA' OR TIPO_FABRICA='procedencia' OR TIPO_FABRICA='COMPRA' or TIPO_FABRICA='compra'))



INSERT INTO CALLE VALUES(1,'COYUYA')
INSERT INTO CALLE VALUES(2,'REFORMA')
INSERT INTO CALLE VALUES(3,'FRAY SERVANDO')

INSERT INTO COMUNA VALUES(1,'BALBUENA')
INSERT INTO COMUNA VALUES(2,'LOMAS')
INSERT INTO COMUNA VALUES(3,'SAN PABLO')

INSERT INTO CIUDAD VALUES(1,'CDMX')
INSERT INTO CIUDAD VALUES(2,'GUANAJUATO')
INSERT INTO CIUDAD VALUES(3,'CHIAPAS')

INSERT INTO CLIENTE VALUES(1800,5000,1500000,0)
INSERT INTO CLIENTE VALUES(1900,380000,2000000,0)


INSERT INTO FROM DIRECCION VALUES(1,1,1,1,1)
INSERT INTO DIRECCION VALUES(2,2,2,2,2)
INSERT INTO DIRECCION VALUES(3,3,3,3,3)

INSERT INTO FABRICA VALUES(100,'x','55545345')
INSERT INTO FABRICA VALUES(200,'y','55323543')


INSERT INTO ARTICULO VALUES(500,'Paquete de hojas')

INSERT INTO  CLI_ART VALUES(500,1900,'25/03/12',1000,820,NULL)

INSERT INTO  ART_FA VALUES(500,100,10000,'COMPRA')


create  procedure pro1 @idart int
as
begin
SELECT NOM_FA,EXISTENCIAS,DESC_ART
FROM FABRICA INNER JOIN ART_FA ON FABRICA.NUM_FA=ART_FA.NUM_FA1 INNER JOIN ARTICULO ON ART_FA.NUM_ART2=ARTICULO.NUM_ART
WHERE NUM_ART=@IDART
end

EXEC pro1 500

create procedure pro2
as
begin
UPDATE CLI_ART
SET TOTAL=PRECIO*CANTIDAD
UPDATE CLIENTE
SET SALDO_CL=SALDO_CL+CLI_ART.TOTAL
FROM CLI_ART INNER JOIN CLIENTE ON CLI_ART.NUM_CL2=CLIENTE.NUM_CL
select NUM_ART1,CANTIDAD,TOTAL,SALDO_CL
FROM CLI_ART INNER JOIN CLIENTE ON CLI_ART.NUM_CL2=CLIENTE.NUM_CL
END

EXEC PRO2

create  procedure PRO3 @ID_ART2 int, @ID_CLI2 INT, @FECHA DATETIME, @CAN INT, @PRE FLOAT, @TOT FLOAT
as
begin
declare @sal float
declare @lc float
select @sal=CLIENTE.SALDO_CL,@lc=CLIENTE.LIMCL
FROM CLIENTE
INSERT INTO CLI_ART VALUES(@ID_ART2,@ID_CLI2,@FECHA,@CAN,@PRE,@TOT)
UPDATE ART_FA
SET EXISTENCIAS=EXISTENCIAS-@CAN
FROM CLI_ART INNER JOIN ARTICULO ON CLI_ART.NUM_ART1=ARTICULO.NUM_ART INNER JOIN ART_FA ON ARTICULO.NUM_ART=ART_FA.NUM_ART2
WHERE NUM_ART1=@ID_ART2 AND NUM_CL2=@ID_CLI2
UPDATE CLI_ART
SET TOTAL=@PRE*@CAN
WHERE NUM_ART1=@ID_ART2 AND NUM_CL2=@ID_CLI2
IF(@sal<@lc)
begin
UPDATE CLIENTE
SET SALDO_CL=SALDO_CL+CLI_ART.TOTAL
FROM CLI_ART INNER JOIN CLIENTE ON CLI_ART.NUM_CL2=CLIENTE.NUM_CL
WHERE NUM_ART1=@ID_ART2 AND NUM_CL2=@ID_CLI2
SELECT *
FROM CLI_ART INNER JOIN CLIENTE ON CLI_ART.NUM_CL2=CLIENTE.NUM_CL  INNER JOIN ARTICULO ON CLI_ART.NUM_ART1=ARTICULO.NUM_ART INNER JOIN ART_FA ON ARTICULO.NUM_ART=ART_FA.NUM_ART2
end
else
begin
SELECT *
FROM CLI_ART INNER JOIN CLIENTE ON CLI_ART.NUM_CL2=CLIENTE.NUM_CL  INNER JOIN ARTICULO ON CLI_ART.NUM_ART1=ARTICULO.NUM_ART INNER JOIN ART_FA ON ARTICULO.NUM_ART=ART_FA.NUM_ART2
end
end

exec pro3 500,1900,'25/03/17',1000,820,null 




