CREATE DATABASE SCHOOL
USE SCHOOL

CREATE TABLE ESCUELA(
CLAVE_E INT PRIMARY KEY,
NOM_E VARCHAR(45),
UBIC_E VARCHAR(45),
CP INT)

INSERT INTO ESCUELA VALUES(1867,'UNIVERSIDAD VICTORIA','CALLE NORTE S/N', 23456)
INSERT INTO ESCUELA VALUES(2875,'ESCUELA PRIMARIA 2','CALLE SU S/N', 77564)
INSERT INTO ESCUELA VALUES(4915,'ESCUELA PRIMARIA 3','CALLE ESTE S/N', 56745)

SELECT ASCII('VIRGINIA')
SELECT ASCII('@CORREO')
SELECT ASCII('MEXICO')
SELECT ASCII('45')
SELECT ASCII('SALVADOR')

SELECT * FROM ESCUELA

SELECT *,ASCII(NOM_E)
FROM ESCUELA

SELECT CHAR(86)+ CHAR(64)
SELECT CHAR(118)
SELECT CHAR(42)
SELECT CHAR(270)

select len('     virginia     ')
SELECT LEN('PRUEBA DE LA FUNCION LEN         ')
SELECT NOM_E,LEN(NOM_E)
FROM ESCUELA

SELECT LTRIM('     PRUEBA DE LA FUNCION LTRIM     ')

INSERT INTO ESCUELA VALUES(27,'     ESCUELA PRIMARIA 5     ','XXXX',1456)
SELECT *
FROM ESCUELA

SELECT LTRIM(NOM_E)
FROM ESCUELA

SELECT *,LTRIM(NOM_E)
FROM ESCUELA
SELECT NOM_E,LTRIM(NOM_E)
FROM ESCUELA

SELECT LTRIM(CLAVE_E) AS CLAVE_E,
LTRIM(NOM_E) AS NOM_E,
LTRIM(UBIC_E) AS UBIC_E,
LTRIM(CP) AS CP
FROM ESCUELA

UPDATE ESCUELA
SET NOM_E= LTRIM(NOM_E)

SELECT *
FROM ESCUELA

SELECT RTRIM('PRUEBA DE LA FUNCION RTRIM     ')

SELECT *, RTRIM(NOM_E) AS INICIALES,
RTRIM(NOM_E) AS FINALES
FROM ESCUELA

UPDATE ESCUELA
SET NOM_E= LTRIM(RTRIM(NOM_E))

SELECT LEFT('VIRGINIA',5)
SELECT LEFT('UNIVERSIDAD',3)

SELECT *,LEFT(NOM_E,15)
FROM ESCUELA

SELECT RIGHT('VIRGINIA',3)
SELECT *,RIGHT(NOM_E,20)
FROM ESCUELA

SELECT SUBSTRING('VIRGINIA',1,1)
SELECT SUBSTRING('VIRGINIA',2,3)
SELECT *
FROM ESCUELA
SELECT SUBSTRING(NOM_E,3,4)
FROM ESCUELA

SELECT LOWER('VIRGINIA')
SELECT LOWER('VirGiNia')

SELECT LOWER(NOM_E)
FROM ESCUELA

UPDATE ESCUELA
SET NOM_E=LOWER(NOM_E)

SELECT *
FROM ESCUELA

select upper('virgina')

SELECT UPPER(NOM_E)
FROM ESCUELA

UPDATE ESCUELA
SET NOM_E=UPPER(NOM_E)

select replace('prueba de reemplazo','e','i')

SELECT REPLACE(NOM_E,'CUE',' ')
FROM ESCUELA

SELECT REPLACE(NOM_E,'CUE','OBSERVAR')
FROM ESCUELA

SELECT REPLICATE('VIRGINIA',5)

SELECT REPLICATE(NOM_E,5)
FROM ESCUELA

SELECT REVERSE('ANITA')

SELECT REVERSE(NOM_E)
FROM ESCUELA

CREATE TABLE CLIENTE(
NUMCLI INT,
NOMBRE VARCHAR(45),
FECHA_NAC DATETIME,
FECHA_ING DATETIME,
MONTO_A FLOAT,
DISPONIBLE FLOAT,
CONSTRAINT PK_NC PRIMARY KEY(NUMCLI))

INSERT INTO CLIENTE VALUES(1,'JUAN CASTILLO ROJAS','12-02-1980','15-09-1995',150000,35000)
INSERT INTO CLIENTE VALUES(2,'VIRGINIA GONZALEZ CASTRO','15-05-1990','15-08-2000',150000,35000)

SELECT *,CHAR(67)+ CHAR(76) + CHAR(73)+LEFT(ASCII(NOMBRE),3) + LEFT(LEN(NOMBRE),45)
FROM CLIENTE

SELECT *,RIGHT(REVERSE(NOMBRE),3)+LEFT(LEN(NOMBRE),45)+LEFT((NOMBRE),3)
FROM CLIENTE