CREATE DATABASE EJEM
USE EJEM

CREATE TABLE PRODUCTO(
ID_P INT PRIMARY KEY,
NOMBRE VARCHAR(45),
PRECIO FLOAT,
FECHA_C DATETIME)

CREATE TABLE CONTACTO(
ID_CONT INT PRIMARY KEY,
NOM_CONT VARCHAR(45),
FECHA_NAC DATETIME)

INSERT INTO PRODUCTO VALUES(1,'COCACOLA',20,'20/12/16')
INSERT INTO PRODUCTO VALUES(2,'PEPSI',30,'21/12/16')
INSERT INTO PRODUCTO VALUES(3,'PLAYMOBIL',240,'22/12/16')
INSERT INTO PRODUCTO VALUES(4,'LEGO',50,'22/12/16 7:16:55:60')

INSERT INTO CONTACTO VALUES(40,'ISAAC','01/10/1996')
INSERT INTO CONTACTO VALUES(41,'RICARDO','18/02/1996')
INSERT INTO CONTACTO VALUES(42,'GERARDO','24/07/1996')
INSERT INTO CONTACTO VALUES(43,'EDGAR','04/08/1994')7

SELECT *,DATEDIFF(YY,FECHA_NAC,GETDATE()) AS EDAD_AÑOS,DATEDIFF(MM,FECHA_NAC,GETDATE()) AS EDAD_MES,DATEDIFF(QQ,FECHA_NAC,GETDATE()) AS EDAD_TRI,
DATEDIFF(WK,FECHA_NAC,GETDATE()) AS EDAD_SEM,
DATEDIFF(DY,FECHA_NAC,GETDATE()) AS EDAD_DIAS,DATEDIFF(HH,FECHA_NAC,GETDATE()) AS EDAD_HORAS,
DATEDIFF(MI,FECHA_NAC,GETDATE()) AS EDAD_MIN,DATEDIFF(SS,FECHA_NAC,GETDATE()) AS EDAD_SEG
FROM CONTACTO


SELECT GETDATE()

SELECT DATEADD(M,-12,GETDATE())
SELECT DATEADD(M,5,GETDATE())

SELECT DATEADD(D,-10,GETDATE())
SELECT DATEADD(yy,10,GETDATE())

SELECT *,DATEADD(YY,5,FECHA_C)
FROM PRODUCTO

SELECT NOMBRE,FECHA_C,
DATEADD(YY,5,FECHA_C) AS AUMENTO_C
FROM PRODUCTO


SELECT NOMBRE,FECHA_C,
DATEADD(QQ,1,FECHA_C) AS AUMENTO_C
FROM PRODUCTO

SELECT NOMBRE,FECHA_C,
DATEADD(WW,2,FECHA_C) AS AUMENTO_C
FROM PRODUCTO


SELECT NOMBRE,FECHA_C,
DATEADD(HH,5,FECHA_C) AS AUMENTO_C
FROM PRODUCTO

SELECT NOMBRE,FECHA_C,
DATEADD(SS,5,FECHA_C) AS AUMENTO_C
FROM PRODUCTO

SELECT *,DATEDIFF
(M,GETDATE(),FECHA_C) AS CADUCIDAD
FROM PRODUCTO

SELECT *,DATEDIFF
(Q,GETDATE(),FECHA_C) AS CADUCIDAD
FROM PRODUCTO

SELECT *,DATEDIFF
(D,GETDATE(),FECHA_C) AS CADUCIDAD
FROM PRODUCTO

SELECT *,DATEDIFF
(YY,GETDATE(),FECHA_C) AS CADUCIDAD
FROM PRODUCTO

SELECT DATENAME(YY,GETDATE())

SELECT DATENAME(MM,GETDATE())

SELECT DATENAME(DD,GETDATE())

SELECT *,DAY(FECHA_NAC)
FROM CONTACTO

SELECT *,MONTH(FECHA_NAC)
FROM CONTACTO

SELECT *,YEAR(FECHA_NAC)
FROM CONTACTO

