CREATE DATABASE hospital1;
USE hospital1;

CREATE TABLE ESPECIALIDAD(
ID_ED int,
NOM_ED VARCHAR(50),
constraint pk_ided primary key(ID_ED))
ENGINE=InnoDB;

CREATE TABLE HORARIO(
ID_HR INT,
NOM_HR VARCHAR(50),
constraint pk_hr primary key(ID_HR))
ENGINE=InnoDB;


CREATE TABLE DOCTOR(
ID_D INT,
NOM_D VARCHAR(150),
CED_D BIGINT,
ID_ED1 INT,
ID_HR1 INT,
constraint pk_dr primary key(ID_D),
CONSTRAINT FK_IDE1 FOREIGN KEY(ID_ED1) REFERENCES ESPECIALIDAD(ID_ED) ON DELETE CASCADE,
CONSTRAINT FK_IDHR1 FOREIGN KEY(ID_HR1) REFERENCES HORARIO(ID_HR) ON DELETE CASCADE ,
CHECK(CED_D>0 AND CED_D<99999))  
ENGINE=InnoDB;


CREATE TABLE DIAGNOSTICO(
ID_DIAG INT,
NOM_DIAG VARCHAR(50),
constraint pk_diag primary key(ID_DIAG))
ENGINE=InnoDB;

CREATE TABLE TIPOTEL(
ID_TEL INT,
TIPO_TEL VARCHAR(50),
constraint pk_tel primary key(ID_TEL))
ENGINE=InnoDB;

CREATE TABLE TIPOENF(
ID_TE INT,
NOM_TE VARCHAR(150),
constraint pk_te primary key(ID_TE))
ENGINE=InnoDB;

CREATE TABLE COLONIA(
ID_COL INT,
NOM_COL VARCHAR(50),
constraint pk_col primary key(ID_COL))
ENGINE=InnoDB;

CREATE TABLE CALLE(
ID_CA INT,
NOM_CALLE VARCHAR(70),
constraint pk_calle primary key(ID_CA))
ENGINE=InnoDB;

CREATE TABLE PRESENTACION(
ID_PRE INT,
NOM_PREN VARCHAR(50),
constraint pk_pre primary key(ID_PRE))
ENGINE=InnoDB;


CREATE TABLE VIAADMON(
ID_VIA INT,
NOM_VA VARCHAR(50),
constraint pl_via primary key(ID_VIA))
ENGINE=InnoDB;

CREATE TABLE LABORATORIO(
ID_LAB INT,
NOM_LAB VARCHAR(50),
constraint pk_lab primary key(ID_LAB))
ENGINE=InnoDB;

CREATE TABLE COMPONENTE(
ID_COM INT,
NOM_COM VARCHAR(50),
constraint pk_com primary key(ID_COM))
ENGINE=InnoDB;


CREATE TABLE UNIDAD(
ID_UN INT,
NOM_UN VARCHAR(50),
NUM_UNI INT,
PRECIO_UNI FLOAT,
TOTAL_UNI FLOAT,
constraint pk_un primary key(ID_UN),
CHECK(NUM_UNI>0),
CHECK(PRECIO_UNI>0),
CHECK(TOTAL_UNI>0))
ENGINE=InnoDB;

CREATE TABLE MEDICAMENTO(
ID_MED INT,
NOM_MED VARCHAR(150),
constraint pk_med primary key(ID_MED))
ENGINE=InnoDB;


CREATE TABLE MEPE(
ID_MED1 INT,
ID_PRE1 INT,
CONSTRAINT FK_IDME1 FOREIGN KEY(ID_MED1) REFERENCES MEDICAMENTO(ID_MED) ON DELETE CASCADE,
CONSTRAINT FK_IPR1 FOREIGN KEY(ID_PRE1) REFERENCES PRESENTACION(ID_PRE) ON DELETE CASCADE)
ENGINE=InnoDB;


CREATE TABLE MEVIAD(
ID_MED2 INT,
ID_VIA1 INT,
CONSTRAINT FK_IDMED2 FOREIGN KEY(ID_MED2) REFERENCES MEDICAMENTO(ID_MED) ON DELETE CASCADE,
CONSTRAINT FK_IDVIA1 FOREIGN KEY(ID_VIA1) REFERENCES VIAADMON(ID_VIA) ON DELETE CASCADE)
ENGINE=InnoDB;



CREATE TABLE MELA(
ID_MED3 INT,
ID_LAB1 INT,
CONSTRAINT FK_IDMED3 FOREIGN KEY(ID_MED3) REFERENCES MEDICAMENTO(ID_MED) ON DELETE CASCADE,
CONSTRAINT FK_IDLAB1 FOREIGN KEY(ID_LAB1) REFERENCES LABORATORIO(ID_LAB) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE MECO(
ID_MED4 INT,
ID_COM1 INT,
CONSTRAINT FK_IDMED4 FOREIGN KEY(ID_MED4) REFERENCES MEDICAMENTO(ID_MED) ON DELETE CASCADE,
CONSTRAINT FK_IDCOM1 FOREIGN KEY(ID_COM1) REFERENCES COMPONENTE(ID_COM) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE MEUN(
ID_MED5 INT,
ID_UN1 INT,
CONSTRAINT FK_IDMED5 FOREIGN KEY(ID_MED5) REFERENCES MEDICAMENTO(ID_MED) ON DELETE CASCADE,
CONSTRAINT FK_IDUN1 FOREIGN KEY(ID_UN1) REFERENCES UNIDAD(ID_UN) ON DELETE CASCADE)
ENGINE=InnoDB;


CREATE TABLE ALERGIA(
ID_AL INT,
NOM_AL VARCHAR(150),
constraint pk_al primary key(ID_AL))
ENGINE=InnoDB;



CREATE TABLE DELEGACION(
ID_DEL INT,
NOM_DEL VARCHAR(150),
constraint pk_del primary key(ID_DEL))
ENGINE=InnoDB;


CREATE TABLE ENFERMEDAD(
ID_EMF INT,
NOM_EMF VARCHAR(50),
constraint pk_emf primary key(ID_EMF))
ENGINE=InnoDB;


CREATE TABLE TIPOPAR(
ID_TPR INT,
NOM_TPR VARCHAR(50),
constraint pk_tpr primary key(ID_TPR))
ENGINE=InnoDB;


CREATE TABLE TIPO_SANGRE(
ID_TS INT,
NOM_TS VARCHAR(50),
constraint pk_sange primary key(ID_TS))
ENGINE=InnoDB;


CREATE TABLE ENFERMO(
CLAVE_ENF INT,
NOM_ENF VARCHAR(200),
FEHE_ENF DATETIME,
FEHS_ENF DATETIME,
ID_CA1 INT,
ID_CO1 INT,
ID_DEL1 INT,
CP_ENF INT,
ID_EN1 INT,
ID_TS1 INT,
constraint pk_enf primary key(CLAVE_ENF),
CONSTRAINT FK_K FOREIGN KEY(ID_CA1) REFERENCES CALLE(ID_CA) ON DELETE CASCADE,
CONSTRAINT FK_CO FOREIGN KEY(ID_CO1) REFERENCES COLONIA(ID_COL) ON DELETE CASCADE,
CONSTRAINT FK_DEL FOREIGN KEY(ID_DEL1) REFERENCES DELEGACION(ID_DEL) ON DELETE CASCADE,
CONSTRAINT FK_N FOREIGN KEY(ID_EN1) REFERENCES TIPOENF(ID_TE) ON DELETE CASCADE,
CONSTRAINT FK_TSO FOREIGN KEY(ID_TS1) REFERENCES TIPO_SANGRE(ID_TS) ON DELETE CASCADE,
CHECK(CP_ENF>0 AND CP_ENF<99999))
ENGINE=InnoDB;

CREATE TABLE  ENFER(
CLAVE_E2 INT,
ID_ENF2 INT,
CONSTRAINT FK_E2 FOREIGN KEY(CLAVE_E2) REFERENCES ENFERMO(CLAVE_ENF) ON DELETE CASCADE,
CONSTRAINT FK_EF2 FOREIGN KEY(ID_ENF2) REFERENCES ENFERMEDAD(ID_EMF) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE TIFER(
CLAVE_E3 INT,
ID_TEL1 INT,
TELEFONO VARCHAR(10),
CONSTRAINT FK_CE7 FOREIGN KEY(CLAVE_E3) REFERENCES ENFERMO(CLAVE_ENF) ON DELETE CASCADE,
CONSTRAINT FK_TE1 FOREIGN KEY(ID_TEL1) REFERENCES TIPOTEL(ID_TEL) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE ALEENF(
CLAVE_E4 INT,
ID_ALE1 INT,
CONSTRAINT FK_CE3 FOREIGN KEY(CLAVE_E4) REFERENCES ENFERMO(CLAVE_ENF) ON DELETE CASCADE,
CONSTRAINT FK_ALE FOREIGN KEY(ID_ALE1) REFERENCES ALERGIA(ID_AL) ON DELETE CASCADE)
ENGINE=InnoDB;


CREATE TABLE TIPOEN(
CLAVE_E5 INT,
ID_TPAR1 INT,
CONSTRAINT FK_RDR FOREIGN KEY(CLAVE_E5) REFERENCES ENFERMO(CLAVE_ENF)ON DELETE CASCADE,
CONSTRAINT FK_AL FOREIGN KEY(ID_TPAR1) REFERENCES TIPOPAR(ID_TPR)ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE ENDIA(
NUM_M INT,
RECON_E VARCHAR(200),
FECHA_PC DATETIME,
FECHA_C DATETIME,
TIEM_E VARCHAR(200),
STAD_E VARCHAR(200),
ID_D1 INT,
ID_DIAG1 INT,
CLAVE_E6 INT,
CONSTRAINT FK_DD FOREIGN KEY(ID_D1) REFERENCES  DOCTOR (ID_D) ON DELETE CASCADE,
CONSTRAINT FK_FR FOREIGN KEY(ID_DIAG1 ) REFERENCES DIAGNOSTICO(ID_DIAG) ON DELETE CASCADE,
CONSTRAINT FK_NN FOREIGN KEY(CLAVE_E6) REFERENCES ENFERMO(CLAVE_ENF) ON DELETE CASCADE)
ENGINE=InnoDB;

CREATE TABLE MEEN(
CLAVE_E7 INT,
ID_MED6 INT,
DOSIS_MR VARCHAR(200),
TIEMPO DATETIME,
CONSTRAINT FK_CL5 FOREIGN KEY(CLAVE_E7) REFERENCES ENFERMO(CLAVE_ENF)ON DELETE CASCADE,
CONSTRAINT FK_FDS FOREIGN KEY(ID_MED6) REFERENCES MEDICAMENTO(ID_MED)ON DELETE CASCADE)
ENGINE=InnoDB;



